### ISSUE TITLE
PMS causes network slowdown?

### ISSUE THREAD

**Issue by telarium** [uglymagoo/plexmediaserver-installer#22] opened 2017-10-13 20:02 UTC
I've tried using this project to install Plex Media Server on an Odroid C2 device, which is ARM64. It does install correctly, but when the service starts at boot, it basically brings down my network so that no traffic gets through. I've tried this with a few different routers and locations, but it happens every time. Disconnecting the ethernet cable immediately solves the problem, as does stopping the PMS service. I also tried disabling features like DLNA and using wifi instead of ethernet, but nothing seems to help.

Users on the Plex forums have found similar issues with x86 operating systems, but for them, either disabling DLNA, trying a different router, or upgrading their Windows 10 network drivers solves the problem.

Has anyone else encountered this behavior with arm devices on their networks? Unfortunately for me it makes Plex not usable.

**Comment by uglymagoo** [comment] 2017-10-13 20:32
According to [this post](https://forums.plex.tv/discussion/291319/plex-1-9-4-4325-debian-swallows-my-entire-internet-upload-bandwidth-without-any-playback-activity#latest) in the plex forum, you just have to be patient. The user mentions 20 minutes on his amd64 server, so it will take much longer on your Odroid ;) I do not know what plex is doing in 1.9.4 and why it requires this much traffic.

Nevertheless, it's not a bug in the installer but in PMS itself so I am closing this issue as there is nothing I can do. Please ask the users in the official [Plex forum](http://forums.plex.tv/discussion/145717/i-have-pms-running-on-raspberry-pi-2#latest).

Btw: are you Plex Pass user? Have you tried 1.9.5?

**Comment by rbhalla** [comment] 2018-04-07 16:41
@telarium I'm encountering the exact same issue (odroid u2). Waiting does not seem to fix it. 

The only reason I'm posting here is because I have a PMS instance running on another device (intel) and it's absolutely fine. 

I'd be interested to know if you ended up fixing it.

**Comment by uglymagoo** [comment] 2018-04-08 01:31
Edit: Not an issue of my package but of your network / router / .... . Please just specify a custom Plex port in the server settings of your ODROID U2 Plex server to disable UPNP port forwarding, what is most likely causing your router to crash.

**Closed as completed** 2018-04-08 01:35 UTC

**Comment by rbhalla** [comment] 2018-04-08 01:55
Hey, yes I definitely should. Just an old device I thought I'd put to good use.

Static IP and manual port is already specified. Unfortunately doesn't help. Oddly the PMS instance on intel has no manual port set and is fine. 

Thanks for looking into it though. If anyone else has any ideas would appreciate any tips.

**Comment by uglymagoo** [comment] 2018-04-08 02:47
For everyone interested, we are continuing the support here: https://forums.plex.tv/discussion/315939/plex-crashing-router
